import { addDays, differenceInDays } from "date-fns";
import { create } from "zustand";
import { persist } from "zustand/middleware";

import type { Contact } from "@/types/contact";
import type { FollowUp } from "@/types/followup";

interface FollowUpsState {
  followUps: FollowUp[];
  createFollowUp: (payload: Omit<FollowUp, "id">) => void;
  completeFollowUp: (id: string) => void;
  snoozeFollowUp: (id: string, days?: number) => void;
  removeFollowUp: (id: string) => void;
  autoGenerateFromContacts: (contacts: Contact[]) => void;
}

function generateSuggestion(contact: Contact, daysSinceLastContact: number): string {
  if (daysSinceLastContact >= 60) return `Вы давно не общались. Уточните у ${contact.name}, какие задачи сейчас в приоритете, и поделитесь полезной мыслью.`;
  if (daysSinceLastContact >= 30) return "Сделайте короткий follow-up и напомните контекст прошлого разговора.";
  return `Поделитесь небольшим инсайтом по теме ${contact.niche ?? "его работы"} и задайте один точный вопрос.`;
}

function generatePriority(daysSinceLastContact: number): FollowUp["priority"] {
  if (daysSinceLastContact >= 60) return "high";
  if (daysSinceLastContact >= 30) return "medium";
  return "low";
}

function suggestBestContactTime(role?: string): string {
  const lower = (role ?? "").toLowerCase();
  if (lower.includes("cto") || lower.includes("engineer") || lower.includes("developer")) return "10:00-12:00 по будням";
  if (lower.includes("founder") || lower.includes("ceo")) return "08:30-10:00 или 18:00-19:00";
  return "11:00-13:00 по местному времени";
}

function daysUntilThisYearDate(date: Date, from: Date): number {
  const target = new Date(from);
  target.setHours(0, 0, 0, 0);
  target.setMonth(date.getMonth(), date.getDate());
  if (target < from) target.setFullYear(target.getFullYear() + 1);
  return differenceInDays(target, from);
}

function makeDedupKey(contactId: string, type: FollowUp["type"], dayKey?: string): string {
  return `${contactId}:${type}:${dayKey ?? "any"}`;
}

export const useFollowUpsStore = create<FollowUpsState>()(
  persist(
    (set, get) => ({
      followUps: [],
      createFollowUp: (payload) =>
        set((state) => ({
          followUps: [...state.followUps, { ...payload, id: crypto.randomUUID() }],
        })),
      completeFollowUp: (id) =>
        set((state) => ({
          followUps: state.followUps.map((f) => (f.id === id ? { ...f, status: "completed" } : f)),
        })),
      snoozeFollowUp: (id, days = 3) =>
        set((state) => ({
          followUps: state.followUps.map((f) =>
            f.id === id ? { ...f, status: "snoozed", scheduledDate: addDays(new Date(f.scheduledDate), days) } : f,
          ),
        })),
      removeFollowUp: (id) => set((state) => ({ followUps: state.followUps.filter((f) => f.id !== id) })),
      autoGenerateFromContacts: (contacts) => {
        const existing = get().followUps.filter((f) => f.status !== "completed");
        const existingKeys = new Set(
          existing.map((f) => makeDedupKey(f.contactId, f.type, new Date(f.scheduledDate).toISOString().slice(0, 10))),
        );
        const now = new Date();
        const autoCreated = contacts.flatMap((contact): FollowUp[] => {
          const generated: FollowUp[] = [];
          const bestTime = suggestBestContactTime(contact.role);

          const birthday = contact.birthday ? new Date(contact.birthday) : undefined;
          if (birthday) {
            const daysLeft = daysUntilThisYearDate(birthday, now);
            if (daysLeft >= 0 && daysLeft <= 7) {
              const date = addDays(now, daysLeft);
              const key = makeDedupKey(contact.id, "birthday", date.toISOString().slice(0, 10));
              if (!existingKeys.has(key)) {
                generated.push({
                  id: crypto.randomUUID(),
                  contactId: contact.id,
                  scheduledDate: date,
                  type: "birthday",
                  status: "pending",
                  aiSuggestion: `Скоро день рождения. Подготовьте теплое поздравление. Оптимальное время: ${bestTime}.`,
                  priority: "high",
                  autoGenerated: true,
                });
              }
            }
          }

          const workAnniversary = contact.workAnniversary ? new Date(contact.workAnniversary) : undefined;
          if (workAnniversary) {
            const daysLeft = daysUntilThisYearDate(workAnniversary, now);
            if (daysLeft >= 0 && daysLeft <= 7) {
              const date = addDays(now, daysLeft);
              const key = makeDedupKey(contact.id, "work-anniversary", date.toISOString().slice(0, 10));
              if (!existingKeys.has(key)) {
                generated.push({
                  id: crypto.randomUUID(),
                  contactId: contact.id,
                  scheduledDate: date,
                  type: "work-anniversary",
                  status: "pending",
                  aiSuggestion: `Скоро годовщина в компании. Поздравьте и спросите о целях на следующий период. Лучшее время: ${bestTime}.`,
                  priority: "medium",
                  autoGenerated: true,
                });
              }
            }
          }

          const hasCheckin = existing.some((f) => f.contactId === contact.id && f.type === "check-in");
          if (hasCheckin) {
            return generated;
          }

          const lastTouch = contact.lastContact ? new Date(contact.lastContact) : new Date(contact.updatedAt);
          const daysSinceLastContact = differenceInDays(now, lastTouch);
          if (daysSinceLastContact < 30) {
            return generated;
          }

          generated.push({
            id: crypto.randomUUID(),
            contactId: contact.id,
            scheduledDate: now,
            type: "check-in",
            status: "pending",
            aiSuggestion: `${generateSuggestion(contact, daysSinceLastContact)} Лучшее время для сообщения: ${bestTime}.`,
            priority: generatePriority(daysSinceLastContact),
            autoGenerated: true,
          });

          return generated;
        });

        if (autoCreated.length === 0) return;
        set((state) => ({ followUps: [...state.followUps, ...autoCreated] }));
      },
    }),
    { name: "founder-crm-followups" },
  ),
);
