"use client";

import { useLLMService } from "@/hooks/use-llm-service";
import { useContactsStore } from "@/store/contacts-store";
import { useFollowUpsStore } from "@/store/followups-store";
import { useSettingsStore } from "@/store/settings-store";

export function useContactAutomation(): { runAutomationForContact: (contactId: string) => Promise<void> } {
  const llm = useLLMService();
  const settings = useSettingsStore((s) => s.settings);
  const getContact = useContactsStore((s) => s.getContact);
  const saveAnalysis = useContactsStore((s) => s.saveAnalysis);
  const createFollowUp = useFollowUpsStore((s) => s.createFollowUp);

  const runAutomationForContact = async (contactId: string): Promise<void> => {
    const contact = getContact(contactId);
    if (!contact) return;

    if (settings.autoCreateFollowUpOnAdd) {
      createFollowUp({
        contactId,
        scheduledDate: new Date(),
        type: "check-in",
        status: "pending",
        priority: "medium",
        autoGenerated: true,
        aiSuggestion: "Приветственный follow-up: отправьте короткое сообщение в течение 24 часов, пока контекст свежий.",
      });
    }

    if (!settings.autoAnalyzeOnAdd) return;
    const hasProviderKey = settings.apiProvider === "openrouter" ? !!settings.openrouterApiKey : !!settings.groqApiKey;
    if (!hasProviderKey) return;

    try {
      const analysis = await llm.analyzeContact(contact);
      saveAnalysis(contactId, analysis);
    } catch {
      // Silent by design for MVP workflow automation.
    }
  };

  return { runAutomationForContact };
}
