export interface FollowUp {
  id: string;
  contactId: string;
  scheduledDate: Date;
  type: "check-in" | "birthday" | "work-anniversary" | "custom";
  status: "pending" | "completed" | "snoozed";
  aiSuggestion?: string;
  priority: "low" | "medium" | "high";
  autoGenerated: boolean;
}
