"use client";

import { useEffect, useMemo } from "react";

import { FollowUpCard } from "@/components/followup/FollowUpCard";
import { Button } from "@/components/ui/button";
import { useContactsStore } from "@/store/contacts-store";
import { useFollowUpsStore } from "@/store/followups-store";
import { useGamificationStore } from "@/store/gamification-store";

export default function FollowUpsPage(): React.JSX.Element {
  const contacts = useContactsStore((s) => s.contacts);
  const { followUps, autoGenerateFromContacts, completeFollowUp, snoozeFollowUp, createFollowUp } = useFollowUpsStore();
  const awardForAction = useGamificationStore((s) => s.awardForAction);
  const incrementGoal = useGamificationStore((s) => s.incrementGoal);
  const resetGoalsIfNeeded = useGamificationStore((s) => s.resetGoalsIfNeeded);

  useEffect(() => {
    resetGoalsIfNeeded();
  }, [resetGoalsIfNeeded]);

  useEffect(() => {
    autoGenerateFromContacts(contacts);
  }, [autoGenerateFromContacts, contacts]);

  const pending = useMemo(
    () =>
      followUps
        .filter((f) => f.status !== "completed")
        .sort((a, b) => new Date(a.scheduledDate).getTime() - new Date(b.scheduledDate).getTime()),
    [followUps],
  );

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-semibold">Напоминания</h1>
        <Button
          variant="outline"
          onClick={() => {
            if (contacts.length === 0) return;
            createFollowUp({
              contactId: contacts[0].id,
              scheduledDate: new Date(),
              type: "custom",
              status: "pending",
              priority: "medium",
              autoGenerated: false,
              aiSuggestion: "Ручное напоминание. Добавьте персональный контекст перед сообщением.",
            });
          }}
        >
          + Вручную
        </Button>
      </div>

      {pending.length === 0 ? (
        <p className="rounded-xl border border-dashed border-zinc-700 p-6 text-center text-sm text-zinc-400">
          Нет активных напоминаний. Добавьте контакты или создайте напоминание вручную.
        </p>
      ) : (
        <div className="space-y-3">
          {pending.map((followUp) => (
            <FollowUpCard
              key={followUp.id}
              followUp={followUp}
              contact={contacts.find((c) => c.id === followUp.contactId)}
              onComplete={() => {
                completeFollowUp(followUp.id);
                awardForAction("completeFollowUp");
                incrementGoal("followups");
              }}
              onSnooze={() => snoozeFollowUp(followUp.id, 3)}
            />
          ))}
        </div>
      )}
    </div>
  );
}
